<<<<<<< HEAD
spring:
  profiles:
    active: dream1
=======
mybatis:
  type-aliases-package: com.so.dreamer.entity
spring:
  application:
    name: spring-cloud-dreamer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 8082
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
>>>>>>> 8611a86e5abdef02d88a1ab4823beec1a1871163
